# Generated by Django 2.1.7 on 2019-02-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='id_name',
        ),
        migrations.AlterField(
            model_name='market',
            name='symbol',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
