# Generated by Django 2.2.2 on 2019-06-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_market', models.CharField(max_length=10)),
                ('order_type', models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], max_length=3)),
                ('price', models.FloatField()),
                ('strategy', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
