# Generated by Django 2.2.2 on 2019-07-03 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0004_auto_20190625_0049'),
        ('orders', '0004_alerttrade_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatictrader',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alerttrade',
            name='order_type',
            field=models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='automatictrader',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_trades', to='exchanges.Account'),
        ),
        migrations.AlterField(
            model_name='automatictrader',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_markets', to='exchanges.Market'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.CharField(max_length=250)),
                ('order_type', models.CharField(max_length=10)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchanges.Account')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='exchanges.Market')),
            ],
        ),
    ]
