# Generated by Django 2.2.2 on 2019-07-05 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190702_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerttrade',
            old_name='order_type',
            new_name='order_side',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_type',
            new_name='order_side',
        ),
        migrations.AlterField(
            model_name='automatictrader',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_trades', to='exchanges.Market'),
        ),
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_orders', to='exchanges.Account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_orders', to='exchanges.Market'),
        ),
    ]
